apiVersion: v1
kind: Service
metadata:
  name: lab4-app
  labels:
    app: lab4
    component: app
spec:
  type: ClusterIP
  selector:
    app: lab4
    component: app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
