apiVersion: v1
kind: ConfigMap
metadata:
  name: lab4-nginx-config
  labels:
    app: lab4
    component: nginx
data:
  default.conf: |
    server {
      listen 8080;

      location /health {
        proxy_pass http://lab4-app:8000/health;
      }

      location / {
        proxy_pass http://lab4-app:8000;
      }
    }
