apiVersion: v1
kind: Service
metadata:
  name: lab4-nginx
  labels:
    app: lab4
    component: nginx
spec:
  type: NodePort
  selector:
    app: lab4
    component: nginx
  ports:
    - name: http
      port: 80
      targetPort: 8080
